# ================================
# Application Configuration
# ================================

environment: "local"

azure:
  account_name: "realtimelog"
  data_container: "data"
  checkpoint_container: "checkpoints"
  sub_prefix: "logs" 
# storage for local env
local:
  data_base: "./data"
  checkpoint_base: "./checkpoints"
  sub_prefix: ""
# storage paths medallion for cloud
paths:
  bronze: "bronze"
  silver_clean: "silver/clean"
  silver_late: "silver/late"
  silver_bad: "silver/bad"
  gold: "gold"


# ================================
# Kafka Configuration
# ================================

kafka:
  bootstrap_servers: "real-time-log.servicebus.windows.net:9093"
  topic: "event-logs"
  # Authentication settings
  security_protocol: "SASL_SSL"
  sasl_mechanism: "PLAIN"
  username: "$ConnectionString"
  starting_offsets: latest

# ================================
# Streaming Configuration
# ================================

streaming:
  trigger_interval: "10 seconds"

  event_time_column: event_time
  watermark_duration: "10 minutes"

  window:
    type: tumbling            # tumbling | sliding
    duration: "5 minute"
    slide: null               # used only if sliding


# ================================
# Deduplication Configuration
# ================================

deduplication:
  enabled: true
  key_columns:
    - event_id
  retention: "5 minutes"
