# ================================
# Application Configuration
# ================================

environment: azure   # local | azure

paths:
  azure:
    bronze: "abfss://data@realtimelog.dfs.core.windows.net/logs/bronze"
    silver:
      clean: "abfss://data@realtimelog.dfs.core.windows.net/logs/silver/clean"
      late:  "abfss://data@realtimelog.dfs.core.windows.net/logs/silver/late"
      bad:   "abfss://data@realtimelog.dfs.core.windows.net/logs/silver/bad"
    gold: "abfss://data@realtimelog.dfs.core.windows.net/logs/gold"

  local:
    bronze: "./data/logs/bronze"
    silver:
      clean: "./data/logs/silver/clean"
      late:  "./data/logs/silver/late"
      bad:   "./data/logs/silver/bad"
    gold: "./data/logs/gold"


checkpoints:
  azure:
    bronze: "abfss://checkpoints@realtimelog.dfs.core.windows.net/bronze"
    silver: "abfss://checkpoints@realtimelog.dfs.core.windows.net/silver"
    gold: "abfss://checkpoints@realtimelog.dfs.core.windows.net/gold"

  local:
    bronze: "./checkpoints/bronze"
    silver:
      clean: "./checkpoints/silver/clean"
      late:  "./checkpoints/silver/late"
      bad:   "./checkpoints/silver/bad"
    gold: "./checkpoints/gold"



# ================================
# Kafka Configuration
# ================================

kafka:
  azure:
    bootstrap_servers: "real-time-log.servicebus.windows.net:9093"
    topic: "app-logs"

    security_protocol: "SASL_SSL"
    sasl_mechanism: "PLAIN"
    username: "$ConnectionString"
    starting_offsets: earliest

  local:
    bootstrap_servers: "localhost:9092"
    topic: "app-logs"

    security_protocol: "PLAINTEXT"
    starting_offsets: latest

# ================================
# Streaming Configuration
# ================================

streaming:
  trigger_interval: "10 seconds"

  event_time_column: event_time
  watermark_duration: "10 minutes"

  window:
    type: tumbling            # tumbling | sliding
    duration: "5 minute"
    slide: null               # used only if sliding


# ================================
# Deduplication Configuration
# ================================

deduplication:
  enabled: true
  key_columns:
    - event_id
  retention: "5 minutes"
